//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 01:54:26 AM EET 
//


package ua.epam.entities;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IsOutskirt" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="EnergyConsumption" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="isCooler" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="AccessoryGroup">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Input"/>
 *               &lt;enumeration value="Output"/>
 *               &lt;enumeration value="Multimedia"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Port">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="COM"/>
 *               &lt;enumeration value="USB"/>
 *               &lt;enumeration value="LPT"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType", propOrder = {
    "isOutskirt",
    "energyConsumption",
    "isCooler",
    "accessoryGroup",
    "port"
})
public class ComplexType {

    @XmlElement(name = "IsOutskirt")
    protected boolean isOutskirt;
    @XmlElement(name = "EnergyConsumption", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger energyConsumption;
    protected boolean isCooler;
    @XmlElement(name = "AccessoryGroup", required = true)
    protected String accessoryGroup;
    @XmlElement(name = "Port", required = true)
    protected String port;

    /**
     * Gets the value of the isOutskirt property.
     * 
     */
    public boolean isIsOutskirt() {
        return isOutskirt;
    }

    /**
     * Sets the value of the isOutskirt property.
     * 
     */
    public void setIsOutskirt(boolean value) {
        this.isOutskirt = value;
    }

    /**
     * Gets the value of the energyConsumption property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEnergyConsumption() {
        return energyConsumption;
    }

    /**
     * Sets the value of the energyConsumption property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEnergyConsumption(BigInteger value) {
        this.energyConsumption = value;
    }

    /**
     * Gets the value of the isCooler property.
     * 
     */
    public boolean isIsCooler() {
        return isCooler;
    }

    /**
     * Sets the value of the isCooler property.
     * 
     */
    public void setIsCooler(boolean value) {
        this.isCooler = value;
    }

    /**
     * Gets the value of the accessoryGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessoryGroup() {
        return accessoryGroup;
    }

    /**
     * Sets the value of the accessoryGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessoryGroup(String value) {
        this.accessoryGroup = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(String value) {
        this.port = value;
    }

}
